version: '3'
services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REWARD_URI=https://goerli-rewardapi.zippie.org
      - SECURE_PREFIX=yourprefix
      - REWARD_TOKEN=0x89E2bb8091232Af7daC4bd473224Ee32AC8147b1
      - ZIPPIE_API_KEY=owner
      - AUTH_KEY=yourauthkey
    entrypoint: 
      - node
      - main.js
